services:
  vscode:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    restart: always
    volumes:
      - .:/code:cached
    expose:
      - "5678"
      - "5679"
    env_file:
      - docker/local/python_api.env
    depends_on:
      - database
      - redis

  database:
    image: postgis/postgis:17-3.5
    restart: always
    env_file:
      - docker/local/python_api.env
    expose:
      - "5432"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  pga:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    expose:
      - "80"
    depends_on:
      - db

  flower:
    image: mher/flower
    restart: always
    expose:
      - "5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis
