
services:
  vscode:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/code:cached
    ports:
      - "5678:5678"
      - "5679:5679"
    env_file:
      - docker/local/python_api.env
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:17-3.5
    env_file:
      - docker/local/python_api.env
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  pga:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis
