# Generated by Django 4.2 on 2025-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("staff", "Staff"), ("client", "Client")],
                default="client",
                max_length=10,
            ),
        ),
    ]
