# Generated by Django 4.2 on 2025-04-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("published_date", models.CharField(max_length=20)),
                ("cover_thumbnail", models.URLField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("copies", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("borrowed", "Borrowed"), ("returned", "Returned")],
                        default="borrowed",
                        max_length=8,
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
